// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bellamart_ecommerce_app.Data;

#nullable disable

namespace bellamart_ecommerce_app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("bellamart_ecommerce_app.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("bellamart_ecommerce_app.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("bellamart_ecommerce_app.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("CustomerName").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("ItemsJson").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("OrderNumber").HasColumnType("INTEGER");
                    b.Property<string>("PaymentMethod").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("PlacedAt").HasColumnType("TEXT");
                    b.Property<decimal>("Total").HasColumnType("TEXT");
                    b.Property<int?>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.ToTable("Orders");
                });

            modelBuilder.Entity("bellamart_ecommerce_app.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount").HasColumnType("TEXT");
                    b.Property<string>("Method").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("OrderId").HasColumnType("INTEGER");
                    b.Property<DateTime>("RecordedAt").HasColumnType("TEXT");
                    b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
                    b.Property<int?>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("OrderId");
                    b.ToTable("Payments");
                });

            modelBuilder.Entity("bellamart_ecommerce_app.Models.Payment", b =>
                {
                    b.HasOne("bellamart_ecommerce_app.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
